CREATE TABLE "sessions" (
	"id" text PRIMARY KEY NOT NULL,
	"uid" integer NOT NULL,
	"csrf_token" text NOT NULL,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"last_seen_at" timestamp with time zone DEFAULT now() NOT NULL,
	"expires_at" timestamp with time zone NOT NULL,
	"ip" text,
	"user_agent" text
);
--> statement-breakpoint
CREATE TABLE "users" (
	"uid" integer PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY (sequence name "users_uid_seq" INCREMENT BY 1 MINVALUE 1 MAXVALUE 2147483647 START WITH 1000 CACHE 1),
	"username" "citext" NOT NULL,
	"email" "citext" NOT NULL,
	"display_name" text,
	"password_hash" text,
	"kind" text DEFAULT 'human' NOT NULL,
	"status" text DEFAULT 'invited' NOT NULL,
	"must_change_password" boolean DEFAULT false NOT NULL,
	"failed_logins" integer DEFAULT 0 NOT NULL,
	"locked_until" timestamp with time zone,
	"created_at" timestamp with time zone DEFAULT now() NOT NULL,
	"updated_at" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "users_username_unique" UNIQUE("username"),
	CONSTRAINT "users_email_unique" UNIQUE("email"),
	CONSTRAINT "users_kind_check" CHECK ("users"."kind" IN ('human', 'service', 'agent')),
	CONSTRAINT "users_status_check" CHECK ("users"."status" IN ('invited', 'active', 'suspended', 'deleted'))
);
--> statement-breakpoint
ALTER TABLE "sessions" ADD CONSTRAINT "sessions_uid_users_uid_fk" FOREIGN KEY ("uid") REFERENCES "public"."users"("uid") ON DELETE cascade ON UPDATE no action;--> statement-breakpoint
CREATE INDEX "sessions_uid_idx" ON "sessions" USING btree ("uid");--> statement-breakpoint
CREATE INDEX "sessions_expires_at_idx" ON "sessions" USING btree ("expires_at");