// Server-side content services: they need the database, so they live behind the
// `@ai-cms/content/service` entry point and stay out of the renderer's import graph.
export {
  diffVersions,
  getContent,
  insertVersion,
  latestVersion,
  listVersions,
  normalizeForNode,
  publish,
  publishVersion,
  publishedVersionId,
  resolveVersion,
  restoreVersion,
  saveDraft,
  unpublish,
  unpublishNode,
  type ContentSnapshot,
  type ContentVersion,
  type PublishHook,
  type PublishOptions,
  type PublishResult,
  type SaveOptions,
  type VersionDiff,
  type VersionInfo,
  type VersionRef,
} from './versions.ts';
export {
  DEFAULT_LAYOUTS,
  DEFAULT_MENU,
  LAYOUTS_PATH,
  MENUS_PATH,
  SITE_SETTINGS_PATH,
  ensureLayout,
  ensureMenu,
  ensureSharedNodes,
  getLayout,
  getMenu,
  getSharedElements,
  getSiteSettings,
  type SharedElements,
  type SharedReadOptions,
} from './shared.ts';
export {
  createPage,
  getPageContext,
  getPageDetails,
  pageStatus,
  savePageMeta,
  userNames,
  type CreatePageInput,
  type PageContext,
  type PageDetails,
  type PageStatus,
  type PageVersionInfo,
} from './pages.ts';
export {
  deletePage,
  getSiteOverview,
  listTreeEntries,
  movePage,
  renamePage,
  saveSiteSettings,
  type SharedEntry,
  type SiteOverview,
  type TreeEntry,
} from './site.ts';
export {
  PlanError,
  executePlan,
  planOperationSchema,
  planSchema,
  type ExecutePlanOptions,
  type PagePreview,
  type PlanIssue,
  type PlanIssueKind,
  type PlanOperation,
  type PlanResult,
  type RenderValidator,
} from './plans.ts';
